-- MySQL Script generated by MySQL Workbench
-- Ср 30 окт 2019 08:06:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema turist_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turist_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turist_db` ;
USE `turist_db` ;

-- -----------------------------------------------------
-- Table `turist_db`.`MarkName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turist_db`.`MarkName` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turist_db`.`Stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turist_db`.`Stages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `pincode` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turist_db`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turist_db`.`Teams` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `turist_db`.`TimeMarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turist_db`.`TimeMarks` (
  `id` INT(11) NOT NULL,
  `mark` TIME NOT NULL,
  `id_Team` INT(11) NOT NULL,
  `id_MarkName` INT(11) NOT NULL,
  `id_Stage` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_TimeMarks_Teams_idx` (`id_Team` ASC) VISIBLE,
  INDEX `fk_TimeMarks_MarkName1_idx` (`id_MarkName` ASC) VISIBLE,
  INDEX `fk_TimeMarks_Stages_idx` (`id_Stage` ASC) VISIBLE,
  CONSTRAINT `fk_TimeMarks_MarkName1`
    FOREIGN KEY (`id_MarkName`)
    REFERENCES `turist_db`.`MarkName` (`id`),
  CONSTRAINT `fk_TimeMarks_Stages`
    FOREIGN KEY (`id_Stage`)
    REFERENCES `turist_db`.`Stages` (`id`),
  CONSTRAINT `fk_TimeMarks_Teams`
    FOREIGN KEY (`id_Team`)
    REFERENCES `turist_db`.`Teams` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `turist_db`.`MarkName`
-- -----------------------------------------------------
START TRANSACTION;
USE `turist_db`;
INSERT INTO `turist_db`.`MarkName` (`id`, `name`) VALUES (1, 'start');
INSERT INTO `turist_db`.`MarkName` (`id`, `name`) VALUES (2, 'finish');
INSERT INTO `turist_db`.`MarkName` (`id`, `name`) VALUES (3, 'stage');

COMMIT;

